//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySendMail
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendMail
    {
        public int SML_SN { get; set; }
        public string SML_Subject { get; set; }
        public string SML_Body { get; set; }
        public string SML_To { get; set; }
        public System.DateTime SML_CAt { get; set; }
        public System.DateTime SML_SendAt { get; set; }
    }
}
